name: Python Telegram Bot CI/CD

on:
  push:
    branches: [main]

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_BOT1 }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
         pip install pyTelegramBotAPI
         
    - name: Run tests
      run: |
        python -m unittest discove


    - name: Deploy to production
      if: success()
      env:
        TELEGRAM_TOKEN: ${{ env.TELEGRAM_TOKEN_BOT1 }}
      run: |
        python bot1.py
